### ISSUE TITLE
Portmaster should use 'make reinstall' to update/reinstall ports when needed.

### ISSUE THREAD

**Issue by kpaasial** [freebsd/portmaster#43]
In its default configuration portmaster will fail to reinstall ports that are required by other installed ports with errors like:

    ===>   libffi-3.2.1 is already installed
          You may wish to ``make deinstall'' and install this port again
          by ``make reinstall'' to upgrade it properly.
          If you really wish to overwrite the old port of libffi
          without deleting it first, set the variable "FORCE_PKG_REGISTER"
          in your environment or the "make install" command line.

The obvious fix is to set FORCE_PKG_REGISTER in /usr/local/etc/portmaster.rc but this is not something the users should need to do. The proper fix would be to use 'make reinstall' for already installed ports, this would make sure the already installed port gets deleted, by force if required.

**Comment by AMDmi3** [comment]
There's no such problem - portmaster updates ports which are required by other ports just fine. Likely your installation is broken, could you post a full log?

**Comment by kpaasial** [comment]
I'm just passing on information from the FreeBSD forums, https://forums.freebsd.org/threads/10-1-release-ezjail-portmaster-issues-with-upgrades.51197/

However, I couldn't reproduce the issue now that I tried it. It's a bit of a mystery why it works for me and is failing for others.

**Comment by kpaasial** [comment]
This can be closed now since I can't even reproduce the issue and it's likely a problem with the jail management software the other person is using.

**Comment by AMDmi3** [comment]
Seems probable. Duplicating what I've said on forum, even if there is portmaster problem, it should never be fixed by using ```make reinstall```

**Comment by bdrewery** [comment]
I agree. `make reinstall` and `FORCE_PKG_REGISTER` are both hammers that should not be used. The need to use them indicates a problem elsewhere.
