### ISSUE TITLE
Add yes to all option to --clean-distfiles

### ISSUE THREAD

**Issue by utkonos** [freebsd/portmaster#45]
For ports like editors/vim that have an absurd number of distfiles (one for each revision), can you add an option to say yes to all future Delete stale file questions?

**Comment by mat813** [comment]
editors/vim is a bad example, as it only has one distfile, as of last week :)
but it would be nice to have anyway.

**Comment by stesser** [comment]
I have been working on a rewrite of portmaster for a long time, and that version does support "a" and "q" for "yes to all" and "no to all" for operations that request user confirmation.
I do not plan to add more features to the current portmaster port, but you could use "--no-confirm -y" to make portmaster delete stale distfiles without asking.
