### ISSUE TITLE
Improve non-interactive usage for pkg messages

### ISSUE THREAD

**Issue by michael-o** [freebsd/portmaster#64]
I am trying to automate jail creation with Bastille which shall install ports via portmaster. Unfortunately portmaster uses `PAGER` with `less(1)` and does not document that unless you look into source code. I was able to circumvent this:
```
CMD env PAGER="/usr/bin/true" portmaster -dG -m -s --no-confirm --no-term-title $(cat /files/ports)
```

I would expect that either `--no-confirm` would disable the pager or a new flag `--non-interactive` would stop asking for any user input.

**Comment by stesser** [comment]
I have updated the port to make --no-confirm omit piping of package messages through the pager (new package version 3.19_29).

**Comment by michael-o** [comment]
> 
> 
> I have updated the port to make --no-confirm omit piping of package messages through the pager (new package version 3.19_29).

Indeed. Is there a reason why it has not been applied in this repo?

**Comment by michael-o** [comment]
I can confirm that this is fixed.
