### ISSUE TITLE
missing 'I' (capital letter i) in getops string

### ISSUE THREAD

**Issue by schmied** [freebsd/portmaster#67]
https://github.com/freebsd/portmaster/blob/b375cf09c7a58d26b2500805206730e21225e38b/portmaster#L743-L752 See also https://github.com/freebsd/portmaster/commit/01f51ec9c02255aa7d68e8cf5b318aa500151cca

**Comment by stesser** [comment]
Thanks! Fixed in commit 64eb6827873b in this repository and commit 793d87945d69 in the FreeBSD ports repository.

**Comment by schmied** [comment]
Thanks for the fast reply!
