### ISSUE TITLE
--no-confirm overwritten in post_first_pass

### ISSUE THREAD

**Issue by Helmut1972** [freebsd/portmaster#68]
Hi,

`portmaster --no-confirm -fBGd -y ca_root_nss`

This unsets PM_NO_CONFIRM in post_first_pass

`unset PM_FIRST_PASS PM_NO_CONFIRM`

displaying the pkg-message after upgrade. Why?

Thank you!

**Comment by stesser** [comment]
Hi Helmut,

I'm not the original author of portmaster, only the maintainer after the author lost interest in it.
Therefore I cannot answer why PM_NO_CONFIRM is being unset with any degree of security.

But you can easily see the author's commit message for that line [here](https://github.com/freebsd/portmaster/commit/477c7c925b452172cfe4981bf019eb96ab06794a).

The "no confirm" option was meant to prevent repeated answers to yes/no questions while portmaster scans for outdated ports and there may be a choice of how to precede.

After the end of the first pass, there will not be any optional questions (for which a yes or no answer could be requested together with --no-confirm or PM_NO_CONFIRM). There will be questions if unexpected issues have been detected, and I do assume that these should not be automatically given the default answer.

But I do see the test for PM_NO_CONFIRM in parent_exit() to control whether the package messages are sent through an actual pager. 

The PAGER variable could  be initialized before PM_NO_CONFIRM is unset.

As a work-around you can also just pass "PAGER=cat" in the environment (or use "PAGER=cat portmaster ...").
I'll put this issue on a list of changes to consider - thanks for reporting ...

**Comment by Helmut1972** [comment]
Works, thank you!

**Comment by stesser** [comment]
Close issue - the FreeBSD port has been updated to version 3.21, which includes this change.
