### ISSUE TITLE
Reproducibile build support for packages

### ISSUE THREAD

**Issue by ghost** [freebsd/portmaster#69]
Would it be possible to set SOURCE_DATE_EPOCH to the TIMESTAMP in distinfo to allow for reproducible package builds?

**Comment by stesser** [comment]
While the TIMESTAMP records when the distinfo has been created/updated, this does not correspond with the date of the last relevant change to a port.
The port's Makefile, default options, dependencies etc. might have changed without TIMESTAMP having been bumped.
If there was a procedure that returned the time of the last relevant change to a port in the main repository, that could be used. But it could only be obtained by fetching Git repository meta-data (and a good strategy which change to consider), which might not even be accessible on a system building the port.
